### ISSUE TITLE
Can't find way to mark nullable element of specific map

### ISSUE THREAD

**Issue by zeldigas** [victools/jsonschema-generator#207]
Documentation contains information about controlling nullability only of fields/methods as a whole, e.g. 
```java
configBuilder.forFields().withNullableCheck(scope -> ....);
```
But I have a bit different scenario:
1. a field `private Map<MyEnum, Map<String, MyPojo>> aField;`
2. I'm generating pattern properties for it, to expand 2 maps and describe fields on pojo
2. I want to set in schema that pojo can be null, so that json/yaml files looks like this
```yml
aField:
  enumVal:
    two: # right now it fails schema validation in Intellij telling that there must be oject but null is provided
```
Unfortunatelly I can't find a way to do it in docs
