### ISSUE TITLE
How to avoid generating methods for non-getters with the maven plugin?

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#397]
Hi, I am autogenerating a bunch of schemas for my model classes using the maven plugin. I am using `lombok` to add `hashCode` and `equals` methods to my model classes. 

I have a class like this:
```java
import lombok.Data;

@Data
public class Dog {
	private int barkVolume;

	public String getBreed() {
		return <calculated-stuff>;
	}
}
```

When I run the maven plugin with these options:
```xml
<options>
  <enabled>
    <option>NONSTATIC_NONVOID_NONGETTER_METHODS</option>
    <option>FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS</option>
  </enabled>
</options>
```

...this is the schema that's generated:
```yaml
properties:
  barkVolume:
    type: integer
  breed:
    type: string
  canEqual(Object):
    type: boolean
  equals(Object):
    type: boolean
  hashCode():
    type: integer
  toString():
    type: string
```

I'm only interested in generating properties for methods that begin with `get...()` that take no arguments. How do I get rid of the other stuff that the schema generator is adding in there beyond `breed`?

(I tested this out on the same [MVE repo](https://github.com/takanuva15/jsonschema-generator-ref-subclass-instead-of-baseclass.git) that I mentioned in my other issue #393.
