### ISSUE TITLE
How to allow one of multiple types for a specific property?

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#398]
Hi, I am using this library to generate schemas for some of my model classes that use the mongodb `ObjectId` class as the type for their id property:
```java
import org.bson.types.ObjectId;

public class MyModel {
	private ObjectId id;
}
```

By default, my APIs will convert it to a String before sending a response, which I can easily configure in this library through
```java
builder
.with(SimpleTypeModule().withStringType(ObjectId.class));
```

However, there is a quirk in some APIs (I'm dealing with legacy code) where it will convert the ObjectId to a json looking like this:
```json
"id": {
  "timestamp": 1502309867,
  "date": 1502309867000
},
```
instead of `"id": "123456"`.

**How can I change the schema-generation config to allow either string or the json object for the `ObjectId` type when it's generating schemas?**

I noticed that there is some override stuff discussed [here](https://victools.github.io/jsonschema-generator/#type-attribute-overrides) in the docs - would it be relevant to this case?
```java
configBuilder.forFields()
    .withTargetTypeOverridesResolver(....
```

**Comment by CarstenWickner** [comment]
Yes exactly, the `TargetTypeOverride` can be used if you have an alternative type that contains those two properties.

Otherwise, a `CustomDefinition` is the more suitable option.

**Comment by takanuva15** [comment]
Unfortunately, I don't have a custom type nor annotations to represent the `ObjectId`, so I'd need to build the schema manually. 

I did some researching based on [this section](https://victools.github.io/jsonschema-generator/#custom-type-definitions) of the docs, but I'm confused how to set up this entire schema:
```
  id:
    anyOf:
      - type: string
      - properties:
          timestamp:
            type: integer
          date:
            type: integer
        required:
          - timestamp
          - date
```
for the `ObjectId` type during schema generation. 

I got this to work for replicating the functionality of `.with(new SimpleTypeModule().withStringType(ObjectId.class))` defined in the following new CustomDefinitionProvider in my code:
```
private class ObjectIdToCustomSchemaProvider implements CustomDefinitionProviderV2 {
	@Override
	public CustomDefinition provideCustomSchemaDefinition(ResolvedType javaType, SchemaGenerationContext context) {
		if (!javaType.isInstanceOf(ObjectId.class)) {
			return null;
		}
		var config = context.getGeneratorConfig();
		var schema = config.createObjectNode().put(context.getKeyword(SchemaKeyword.TAG_TYPE), context.getKeyword(SchemaKeyword.TAG_TYPE_STRING));
		return new CustomDefinition(schema, true);
	}
}
```

Yet when I try to put an array in there for the `anyOf`, it's throwing compile errors which I'm not sure how to work around:
```
private class ObjectIdToCustomSchemaProvider implements CustomDefinitionProviderV2 {
	@Override
	public CustomDefinition provideCustomSchemaDefinition(ResolvedType javaType, SchemaGenerationContext context) {
		if (!javaType.isInstanceOf(ObjectId.class)) {
			return null;
		}
		var config = context.getGeneratorConfig();
		var schema = config.createObjectNode().put(context.getKeyword(SchemaKeyword.TAG_ANYOF),
				config.createArrayNode()
		);
		return new CustomDefinition(schema, true);
	}
}
```

I pushed this updated code to the same [MVE repo](https://github.com/takanuva15/jsonschema-generator-ref-subclass-instead-of-baseclass) as before.

**Comment by CarstenWickner** [comment]
HI @takanuva15,

The compilation error can be avoided by splitting that line into two, to ensure the `schema` variable is only the main `ObjectNode` and not the `ArrayNode`.
Also: rather use `.set()` or `.putArray()` instead of the deprecated `.put()`
```java
var schema = config.createObjectNode();
var anyOf = schema.set(context.getKeyword(SchemaKeyword.TAG_ANYOF), config.createArrayNode());
return new CustomDefinition(schema, true);
```

Overall, I'd say you have two basic options for handling this:

### Option 1: complete manual schema generation as `CustomDefinition`
``´java
	private class ObjectIdToCustomSchemaProvider implements CustomDefinitionProviderV2 {
		@Override
		public CustomDefinition provideCustomSchemaDefinition(ResolvedType javaType, SchemaGenerationContext context) {
			if (!javaType.isInstanceOf(ObjectId.class)) {
				return null;
			}
			var config = context.getGeneratorConfig();
			var schema = config.createObjectNode();
			var anyOf = schema.putArray(context.getKeyword(SchemaKeyword.TAG_ANYOF));
			anyOf.addObject()
					.put(context.getKeyword(SchemaKeyword.TAG_TYPE), context.getKeyword(SchemaKeyword.TAG_TYPE_STRING));
			ObjectNode secondTypeNode = anyOf.addObject();
			ObjectNode objectProperties = secondTypeNode
					.put(context.getKeyword(SchemaKeyword.TAG_TYPE), context.getKeyword(SchemaKeyword.TAG_TYPE_OBJECT))
					.putObject(context.getKeyword(SchemaKeyword.TAG_PROPERTIES));
			objectProperties.put("timestamp",
					context.createStandardDefinitionReference(context.getTypeContext().resolve(Integer.class), this));
			objectProperties.put("date",
					context.createStandardDefinitionReference(context.getTypeContext().resolve(Integer.class), this));
			secondTypeNode.putArray(context.getKeyword(SchemaKeyword.TAG_REQUIRED))
					.add("timestamp").add("date");
			return new CustomDefinition(schema, true);
		}
	}
```
This produces the desired schema:
```yaml
---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  barkVolume:
    type: integer
  breed:
    type: string
  id:
    anyOf:
    - type: string
    - type: object
      properties:
        timestamp:
          type: integer
        date:
          type: integer
      required:
      - timestamp
      - date
  name:
    type: string
  numLegs:
    type: integer
unevaluatedProperties: false
```

### Option 2: Target Type Override with inline type
```java
public class GeneralConfigModule implements Module {
	@Override
	public void applyToConfigBuilder(SchemaGeneratorConfigBuilder builder) {
		builder.forFields()
				.withTargetTypeOverridesResolver(this::collectTargetTypeOverrides);
		builder.forMethods()
				.withTargetTypeOverridesResolver(this::collectTargetTypeOverrides)
				.withIgnoreCheck(method -> method.getSchemaPropertyName().endsWith(")"));
	}

	private List<ResolvedType> collectTargetTypeOverrides(MemberScope<?, ?> member) {
		if (member.getType() == null || !member.getType().isInstanceOf(ObjectId.class)) {
			return null;
		}
		return Stream.of(String.class, ObjectIdRepresentation.class)
				.map(member.getContext()::resolve)
				.collect(Collectors.toList());
	}

	private static class ObjectIdRepresentation {
		@NotNull protected int date;
		@NotNull protected int timestamp;
	}
}
```
For the second option, I included the `JakartaValidationModule` with the option `NOT_NULLABLE_FIELD_IS_REQUIRED` in order to achieve the two properties being marked as `required` and thereby achieve the same generated schema.
I've created a [PR with both options on your repository](https://github.com/takanuva15/jsonschema-generator-ref-subclass-instead-of-baseclass/pull/2).

**Comment by takanuva15** [comment]
Incredible! You are a boss sir. 

One thing I'm realizing with Option 1 is that I could just save my custom schema as a resource file and then read that into the DefinitionProvider at runtime so I won't need to write as much code in the `CustomDefinitionProviderV2`.

One related question after doing some experimenting just now: If I don't provide any custom module or DefinitionProvider for `ObjectId.java`, then it generates the following schema for `id` which is very close:
```
id:
  type: object
  properties:
    counter:
      type: integer
    date:
      type: string
    randomValue1:
      type: integer
    randomValue2:
      type: integer
    timestamp:
      type: integer
```

This is very close (the extra properties it added are fine ok for me), but it's just missing `type: string` as an option under an `anyOf` array. Is there a way to sort of "shift" this default generated schema under a new `anyOf` array so I can just add `type: string` as an alternate option to this schema for `id`?

**Comment by CarstenWickner** [comment]
Hi @takanuva15,

That would simplify it indeed:
```java
private class ObjectIdToCustomSchemaProvider implements CustomDefinitionProviderV2 {
	@Override
	public CustomDefinition provideCustomSchemaDefinition(ResolvedType javaType, SchemaGenerationContext context) {
		if (!javaType.isInstanceOf(ObjectId.class)) {
			return null;
		}
		var schema = context.getGeneratorConfig().createObjectNode();
		Stream.of(String.class, ObjectId.class)
				.map(context.getTypeContext()::resolve)
				.map(anyOfOption -> context.createStandardDefinition(anyOfOption, this))
				.forEach(schema.putArray(context.getKeyword(SchemaKeyword.TAG_ANYOF))::add);
		return new CustomDefinition(schema, true);
	}
}
```
That results in the following schema:
```yaml
---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  barkVolume:
    type: integer
  breed:
    type: string
  id:
    anyOf:
    - type: string
    - type: object
      properties:
        counter:
          type: integer
        date:
          type: string
        randomValue1:
          type: integer
        randomValue2:
          type: integer
        timestamp:
          type: integer
  name:
    type: string
  numLegs:
    type: integer
unevaluatedProperties: false
```
