### ISSUE TITLE
Using `Jackson` module seems to remove parent class properties from subtype schema?

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#403]
Hi, I'm using this plugin to generate a bunch of schemas for my model classes. I have a situation where I have an abstract class `Animal` and a subtype `Dog`. By default, the generated schema for `Dog` includes the `Animal` type's props. However, once I add the `Jackson` module, suddenly the `Dog` schema no longer contains the props of `Animal`. Is there a Jackson option I'm missing?

Dog:
```java
@Data
public class Dog extends Animal {
	@JsonProperty("bark_volume")
	private int barkVolume;

	public String getBreed() {
		return "labrador";
	}
}
```
Animal:
```java
public abstract class Animal {
	protected String name;
	protected int numLegs;
}
```

Generated dog schema:
```yaml
$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  bark_volume:
    type: integer
  breed:
    type: string
```
(Without the Jackson module, the dog schema would have "name" and "numLegs" in it)

I've added this code into my [MVE repo](https://github.com/takanuva15/jsonschema-generator-ref-subclass-instead-of-baseclass) to replicate the issue.
