### ISSUE TITLE
How to access scope.isFakeContainerItemScope when generating custom schemas for $ref?

### ISSUE THREAD

**Issue by takanuva15** [victools/jsonschema-generator#475]
Hi, in the [`ExternalRefPackageExample.java`](https://github.com/victools/jsonschema-generator/blob/main/jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/ExternalRefPackageExample.java) sample code, we are able to set up `$refs` to other schemas so that we don't duplicate schemas between connected models. 

I would like to customize this code so that when it generates a $ref for an array, the schema is different than when it generates a $ref for a regular object.

Here's a quick example:
`PetStore.java`
```java
public class PetStore {
        private Cat mascot;
	private List<Cat> pets;
}

public class Cat {
	private int numWhiskers;
}
```

What I want to generate for Petstore schema:
`PetStore-schema.yml`
```yml
$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  mascot:
    allOf:
    - $ref: Cat-schema.yml
  pets:
    type: array
    items:
      $ref: Cat-schema.yml
```

Unfortunately with the linked example, it forces both refs to have the exact same format. If I could acces the `isFakeContainerItemScope` method in there, I could change the schema getting generated for one ref vs the other. 

Is there a way to make that possible?
